server : rconto_corrente_server.c
	gcc -o server rconto_corrente_server.c -std=c17 -g3 -Wall -Werror -pedantic -D_FORTIFY_SOURCE=2

client : rconto_corrente_client.c
	gcc -o client rconto_corrente_client.c -std=c17 -g3 -Wall -Werror -pedantic -D_FORTIFY_SOURCE=2

clean : 
	rm client server
