server : rdisponibilita_vini_server.c
	gcc -o server rdisponibilita_vini_server.c -std=c17 -g3 -Wall -Werror -pedantic -D_FORTIFY_SOURCE=2

client : rdisponibilita_vini_client.c
	gcc -o client rdisponibilita_vini_client.c -std=c17 -g3 -Wall -Werror -pedantic -D_FORTIFY_SOURCE=2

clean : 
	rm client server
